[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "nft"
  included_files = ["views/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
